name: gocheck
description: Runs a series of checks on a Go repository.
runs:
inputs:
  repository-url:
    description: 'Who to greet'
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
  - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
  - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  - name: Check out repository code
    uses: actions/checkout@v2
    with:
      path: myrepo
      submodules: true  # Fetch Hugo themes (true OR recursive)
      fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
  - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
  - run: echo "🖥️ The workflow is now ready to test your code on the runner."
  - name: Set up Go
    uses: actions/setup-go@v2
    with:
      go-version: 1.17
  - name: Run all.bash
    run: |
      pushd myrepo
      ./checks.bash
      ls ${{ github.workspace }}
      popd
