name: Run CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository first
      # Otherwise the workflow won't be able to find the action
      - uses: actions/checkout@v2
      - name: List files in the public repository
        run: |
          pushd gocheck
          ls -alh
          popd
      - uses: ./action.yml
